config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  root 'application#home'
  post "sign_up", to: "users#create"
  get "sign_up", to: "users#new"
  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"
  resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token
  put "account", to: "users#update"
  get "account", to: "users#edit"
  delete "account", to: "users#destroy"
  resources :active_sessions, only: [:destroy] do
    collection do
      delete "destroy_all"
    end
  end
  get 'static_pages/home'
  resources :posts
end

app/models/user.rb
class User < ApplicationRecord
  CONFIRMATION_TOKEN_EXPIRATION = 10.minutes
  MAILER_FROM_EMAIL = "no-reply@example.com"
  PASSWORD_RESET_TOKEN_EXPIRATION = 10.minutes

  attr_accessor :current_password


  before_save :downcase_unconfirmed_email

  has_many :active_sessions, dependent: :destroy
  has_secure_password
  #has_many :posts, dependent: :destroy
  has_many :posts, class_name: "Post", foreign_key: "user_id", dependent: :destroy
  # has_secure_token :remember_token

  before_save :downcase_email

  validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, presence: true, uniqueness: true
  validates :unconfirmed_email, format: {with: URI::MailTo::EMAIL_REGEXP, allow_blank: true}

  def confirm!
    if unconfirmed_or_reconfirming?
      if unconfirmed_email.present?
        return false unless update(email: unconfirmed_email, unconfirmed_email: nil)
      end
      update_columns(confirmed_at: Time.current)
    else
      false
    end
  end

  def self.authenticate_by(attributes)
    passwords, identifiers = attributes.to_h.partition do |name, value|
      !has_attribute?(name) && has_attribute?("#{name}_digest")
    end.map(&:to_h)

    raise ArgumentError, "One or more password arguments are required" if passwords.empty?
    raise ArgumentError, "One or more finder arguments are required" if identifiers.empty?
    if (record = find_by(identifiers))
      record if passwords.count { |name, value| record.public_send(:"authenticate_#{name}", value) } == passwords.size
    else
      new(passwords)
      nil
    end
  end

  def confirmed?
    # debugger
    confirmed_at.present?
  end

  def confirmable_email
    if unconfirmed_email.present?
      unconfirmed_email
    else
      email
    end
  end

  def reconfirming?
    unconfirmed_email.present?
  end

  def unconfirmed_or_reconfirming?
    unconfirmed? || reconfirming?
  end

  def generate_confirmation_token
    # https://api.rubyonrails.org/classes/ActiveRecord/SignedId.html#method-i-signed_id
    # In-built method
    signed_id expires_in: CONFIRMATION_TOKEN_EXPIRATION, purpose: :confirm_email
  end

  def generate_password_reset_token
    signed_id expires_in: PASSWORD_RESET_TOKEN_EXPIRATION, purpose: :reset_password
  end

  def send_password_reset_email!
    password_reset_token = generate_password_reset_token
    UserMailer.password_reset(self, password_reset_token).deliver_now
  end

  def unconfirmed?
    !confirmed?
  end

  def send_confirmation_email!
    confirmation_token = generate_confirmation_token
    UserMailer.confirmation(self, confirmation_token).deliver_now
  end

  private

  def downcase_email
    self.email = email.downcase
  end

  def downcase_unconfirmed_email
    return if unconfirmed_email.nil?
    self.unconfirmed_email = unconfirmed_email.downcase
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :destroy, :update]

  def create
    @user = User.new(create_user_params)
    if @user.save
      @user.send_confirmation_email!
      render json: @user, status: :created
    else
      Rails.logger.error(@user.errors.full_messages.to_sentence)
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    current_user.destroy
    reset_session
    redirect_to root_path, notice: "Your account has been deleted."
  end

  def edit
    @user = current_user
    @active_sessions = @user.active_sessions.order(created_at: :desc)
  end

  def new
    @user = User.new
  end

  def update
    @user = current_user
    @active_sessions = @user.active_sessions.order(created_at: :desc)
    if @user.authenticate(params[:user][:current_password])
      if @user.update(update_user_params)
        if params[:user][:unconfirmed_email].present?
          @user.send_confirmation_email!
          redirect_to root_path, notice: "Check your email for confirmation instructions."
        else
          redirect_to root_path, notice: "Account updated."
        end
      else
        render :edit, status: :unprocessable_entity
      end
    else
      flash.now[:error] = "Incorrect password"
      render :edit, status: :unprocessable_entity
    end
  end

  private
  
  def create_user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def update_user_params
    params.require(:user).permit(:name, :current_password, :password, :password_confirmation, :unconfirmed_email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
.container
  %h2 Current Logins
  - if @active_sessions.any?
    = button_to 'Log out of all other sessions', destroy_all_active_sessions_path, method: :delete, class: 'btn btn-danger'
    %table.table
      %thead
        %tr
          %th User Agent
          %th IP Address
          %th Signed In At
          %th Sign Out
      %tbody
        = render @active_sessions

  .card
    .card-header
      %h3.card-title Update Account
    .card-body
      = form_with model: @user, url: account_path, method: :put, html: { class: 'form-horizontal' } do |form|
        = render partial: 'shared/form_errors', locals: { object: form.object }

        .form-group
          = form.label :email, 'Current Email', class: 'form-label'
          = form.email_field :email, disabled: true, class: 'form-control'

        .form-group
          = form.label :name, 'Current Name', class: 'form-label'
          = form.text_field :name, class: 'form-control'

        .form-group
          = form.label :unconfirmed_email, 'New Email', class: 'form-label'
          = form.text_field :unconfirmed_email, class: 'form-control'

        .form-group
          = form.label :password, "Password (leave blank if you don't want to change it)", class: 'form-label'
          = form.password_field :password, class: 'form-control'

        .form-group
          = form.label :password_confirmation, class: 'form-label'
          = form.password_field :password_confirmation, class: 'form-control'

        %hr

        .form-group
          = form.label :current_password, 'Current password (we need your current password to confirm your changes)', class: 'form-label'
          = form.password_field :current_password, required: true, class: 'form-control'

        = form.submit 'Update Account', class: 'btn btn-primary mt-2'

app/views/users/new.html.haml
.container.mt-5
  .row.justify-content-center
    .col-md-6
      .card
        .card-header
          %h3.card-title Sign Up
        .card-body
          = form_with model: @user, url: sign_up_path, class: 'form-horizontal', format: :html do |form|
            = render partial: 'shared/form_errors', locals: { object: form.object }
            .form-group.mb-3
              = form.label :name, class: 'form-label'
              = form.text_field :name, required: true, class: 'form-control'
            .form-group.mb-3
              = form.label :email, class: 'form-label'
              = form.email_field :email, required: true, class: 'form-control'
            .form-group.mb-3
              = form.label :password, class: 'form-label'
              = form.password_field :password, required: true, class: 'form-control'
            .form-group.mb-3
              = form.label :password_confirmation, class: 'form-label'
              = form.password_field :password_confirmation, required: true, class: 'form-control'
            .d-grid
              = form.submit 'Sign Up', class: 'btn btn-primary'