config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  root 'application#home'
  post "sign_up", to: "users#create"
  get "sign_up", to: "users#new"
  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"
  resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token
  put "account", to: "users#update"
  get "account", to: "users#edit"
  delete "account", to: "users#destroy"
  resources :active_sessions, only: [:destroy] do
    collection do
      delete "destroy_all"
    end
  end
  get 'static_pages/home'
  resources :posts
end

app/views/shared/_flash_messages.html.haml
- flash.each do |key, message|
  .flash{ class: key }
    = message
    %span.close-flash.cross-btn-icon
      X
:css
  .flash {
    padding: 15px 20px 15px 20px;
    margin: 10px 0;
    border-radius: 5px;
    position: absolute;
    right: 0;
    z-index: 1;
  }

  .flash.notice {
    background-color: #e7f5ff;
    color: #31708f;
  }

  .flash.alert {
    background-color: #f8d7da;
    color: #a94442;
  }

  .cross-btn-icon {
    color: gray;
    vertical-align: middle;
    font-size: 18px;
    margin-left: 10px;
    font-weight: 500;
    cursor: pointer;
  }

-# :javascript
-#   document.addEventListener('DOMContentLoaded', function() {
-#     const closeButton = document.querySelector(".close-flash");
-#     if (closeButton) {
-#       closeButton.addEventListener('click', function(event) {
-#         document.querySelector(".flash").style.display = 'none';
-#       });
-#     }
-#   });

app/views/shared/_form_errors.html.haml
- if object.errors.any?
  - debugger 
  %ul
  - object.errors.full_messages.each do |message|
    %li= message

app/views/shared/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    = link_to root_path, class: 'navbar-brand' do
      %i.fas.fa-flag
      Brand
    %button.navbar-toggler{type: "button", "data-bs-toggle" => "collapse", "data-bs-target" => "#navbarSupportedContent", "aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.me-auto
        = link_to root_path, class: "nav-link #{'active fw-bold' if current_page?(root_path)}" do
          .fa.fa-home
          Home
        - if params[:controller] == 'posts' && params[:action] == 'index'
          = link_to new_post_path, class: "nav-link #{'active fw-bold' if current_page?(new_post_path)}" do
            .fa.fa-home
            Create Post
      %ul.navbar-nav.ms-auto
        - if current_user
          %li.nav-item.dropdown
            %a.nav-link.dropdown-toggle{href: "#", id: "navbarDropdown", role: "button", "data-bs-toggle" => "dropdown", "aria-expanded" => "false"}
              .fa.fa-user
              %b= current_user.name
            %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
              = link_to account_path, class: "dropdown-item #{'active fw-bold' if current_page?(account_path)}" do
                .fa.fa-cog
                %b Account settings
              = link_to logout_path, method: :delete, class: 'dropdown-item' do
                .fa.fa-sign-out-alt
                %b Sign out
        - else
          = link_to 'Log in', login_path, class: "nav-link #{'active fw-bold' if current_page?(login_path)}"
          = link_to 'Sign up', sign_up_path, class: "nav-link #{'active fw-bold' if current_page?(sign_up_path)}"